### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cursors' of undefined

### ISSUE THREAD

**Issue by bradfx** [bradleyflood/auto-id-class#2]
[Enter steps to reproduce below:]
1. `.` in `cmd+p` file search.. I think

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [auto-id-class](https://github.com/bradleyflood/auto-id-class) package, v0.2.5
### Stack Trace

Uncaught TypeError: Cannot read property 'cursors' of undefined

```
At /Users/bradleyflood/.atom/packages/auto-id-class/lib/auto-id-class.coffee:51

TypeError: Cannot read property 'cursors' of undefined
  at Object.module.exports.AutoIdClass.cursor_inside_html_tag (/Users/bradleyflood/.atom/packages/auto-id-class/lib/auto-id-class.coffee:51:14)
  at Object.module.exports.AutoIdClass.insert_class_attribute (/Users/bradleyflood/.atom/packages/auto-id-class/lib/auto-id-class.coffee:37:9)
  at atom-text-editor.subscriptions.add.atom.commands.add.auto-id-class:insert_class_attribute (/Users/bradleyflood/.atom/packages/auto-id-class/lib/auto-id-class.coffee:20:51)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
  3x -1:44.6.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:42.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -1:42.1.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -1:34.8.0 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:33.7.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:12.1.0 core:copy (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -1:11.4.0 core:undo (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:09.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -1:06.9.0 core:close (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:59.3.0 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:58.8.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:58.1.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 10x -0:57.4.0 core:close (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.1.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:01.2.0 auto-id-class:insert_class_attribute (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-jshint",
      "linter"
    ],
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
auto-id-class, v0.2.5
docblockr, v0.7.3
emmet, v2.3.12
vim-mode, v0.58.0

# Dev
No dev packages
```

**Comment by dsandstrom** [comment]
Also getting these errors.  A related issue: if the last cursor is in an html tag, it will start a class for that tag.  Even though I'm typing in the search toolbar.

**Comment by bradfx** [comment]
Thanks @dsandstrom. I'll look into this and have created #3 as well.
